apiVersion: v1
kind: Service
metadata:
  name: tensorboard-hp
  labels:
    name: tensorboard-hp
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 6006
  selector:
    app: tensorboard-hp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tensorboard-hp
  name: tensorboard-hp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorboard-hp
  template:
    metadata:
      labels:
        app: tensorboard-hp
    spec:
      volumes:
        - name: azure-files
          azureFile:
            secretName: azure-file-secret
            shareName: hyperparam1
            readOnly: false 
      containers:
      - name: tensorboard-hp
        image: gotcr.azurecr.io/chzbrgr71/tensorboard:2.00
        imagePullPolicy: Always
        command:
         - /usr/local/bin/tensorboard
        args:
        - --logdir
        - /tf-output
        volumeMounts:
          - mountPath: /tf-output
            name: azure-files
        ports:
        - containerPort: 6006
          protocol: TCP
      restartPolicy: Always