apiVersion: batch/v1
kind: Job
metadata:
  name: got-convert-model
spec:
  template:
    metadata:
    spec:
      containers:
      - name: got-convert-model
        image: briaracr.azurecr.io/chzbrgr71/tflite-convert:1.0
        args:
          - "--graph_def_file=/tf-output/latest_model/got_retrained_graph.pb"
          - "--output_file=/tf-output/latest_model/optimized_graph.lite"
          - "--input_format=TENSORFLOW_GRAPHDEF"
          - "--output_format=TFLITE"
          - "--input_shape=1,299,299,3"
          - "--input_array=Mul"
          - "--output_array=final_result"
          - "--inference_type=FLOAT"
          - "--input_data_type=FLOAT"
        volumeMounts:
        - mountPath: /tf-output
          name: azure-files            
      restartPolicy: Never     
      volumes:
        - name: azure-files
          azureFile:
            secretName: azure-file-secret
            shareName: aksshare
            readOnly: false 