apiVersion: batch/v1
kind: Job
metadata:
  name: got-image-training-job-vk
spec:
  template:
    metadata:
    spec:
      containers:
      - name: got-image-training-job-vk
        image: chzbrgr71/got-image-training:1.63
        command: ["python","retrain.py"]
        args:                
          - "--bottleneck_dir=/tmp/tensorflow/bottlenecks"
          - "--model_dir=/tmp/tensorflow/inception"
          - "--summaries_dir=/tf-output"
          - "--output_graph=/tf-output"
          - "--output_labels=/tf-output"
          - "--image_dir=/images"
          - "--saved_model_dir=/tf-output"
        volumeMounts:
        - mountPath: /tf-output
          name: azure-files
        env:
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name               
      restartPolicy: Never     
      volumes:
        - name: azure-files
          azureFile:
            secretName: azure-file-secret
            shareName: aksshare
            readOnly: false 
      nodeSelector: # for VK
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations: # for VK
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule               