apiVersion: batch/v1
kind: Job
metadata:
  name: got-image-training-job
spec:
  template:
    metadata:
    spec:
      containers:
      - name: got-image-training-job
        #image: briaracr.azurecr.io/chzbrgr71/got-image-training:1.63
        image: chzbrgr71/got-image-training:1.63
        args:                
          - "--bottleneck_dir=/tmp/tensorflow/bottlenecks"
          - "--model_dir=/tmp/tensorflow/inception"
          - "--summaries_dir=/tf-output"
          - "--output_graph=/tf-output"
          - "--output_labels=/tf-output"
          - "--image_dir=/images"
          - "--saved_model_dir=/tf-output"
        volumeMounts:
        - mountPath: /tf-output
          name: azure-files
        env:
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name               
      restartPolicy: Never     
      volumes:
        - name: azure-files
          azureFile:
            secretName: azure-file-secret
            shareName: aksshare
            readOnly: false 