apiVersion: kubeflow.org/v1beta2
kind: TFJob
metadata:
  name: got-image-training
  namespace: default
spec:
  tfReplicaSpecs:
    Worker:
      replicas: 1
      template:
        spec:
          containers:
          - args:
            - "--bottleneck_dir=/tmp/tensorflow/bottlenecks"
            - "--model_dir=/tmp/tensorflow/inception"
            - "--summaries_dir=/tf-output"
            - "--output_graph=/tf-output"
            - "--output_labels=/tf-output"
            - "--image_dir=/images"
            - "--saved_model_dir=/tf-output"
            image: chzbrgr71/got-image-training:1.63
            name: tensorflow
            env:
            - name: KUBE_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name