image:
  repository: microsoft/virtual-kubelet
  tag: aci-gpu.0.1
  pullPolicy: Always

## `provider` should be one of aws, azure, azurebatch, etc...
provider: azure
nodeName: "virtual-node"
nodeOsType: "Linux"
monitoredNamespace: ""
apiserverCert: 
apiserverKey: 
logLevel: 

taint:
  enabled: true
  key: virtual-kubelet.io/provider
  value: "{{ .Values.provider }}"
  ## `effect` must be `NoSchedule`, `PreferNoSchedule` or `NoExecute`.
  effect: NoSchedule

providers:
  azure:
    ## Set to true if deploying to Azure Kubernetes Service (AKS), otherwise false
    targetAKS: true
    clientId: 59343209-9d9e-464d-8508-068a3d331fb9
    clientKey: d55a7984-3500-4f16-ace4-55414d2d6446
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
    subscriptionId: 471d33fd-a776-405b-947c-467c291dc741
    ## `aciResourceGroup` and `aciRegion` are required only for non-AKS deployments
    aciResourceGroup: aci
    aciRegion: centralus
    masterUri: 
    loganalytics:
      enabled: false
      workspaceId: 
      workspaceKey: 
      clusterResourceId: 
    vnet:
      enabled: false
      subnetName: 
      subnetCidr: 
      clusterCidr: 
      kubeDnsIp: 

## Install Default RBAC roles and bindings
rbac:
  install: true
  serviceAccountName: virtual-kubelet
  ## RBAC api version
  apiVersion: v1beta1
  ## Cluster role reference
  roleRef: cluster-admin